//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyWarehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public System.Guid Id { get; set; }
        public System.Guid part_id { get; set; }
        public int quantity { get; set; }
    
        public virtual part part { get; set; }
    }
}
