//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyWarehouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public part()
        {
            this.inventory = new HashSet<inventory>();
            this.transaction = new HashSet<transaction>();
        }
    
        public System.Guid Id { get; set; }
        public string part_number { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public Nullable<decimal> weight { get; set; }
        public System.DateTime created_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory> inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transaction { get; set; }
    }
}
